"""Integration tests for data manager processing with real data."""

import pytest
import tempfile
import shutil
from pathlib import Path
from datetime import date, timedelta
import polars as pl
import numpy as np
from unittest.mock import patch
from definitions import ROOT_DIR

from data_manager.processing.incremental_orderbook_sampler import IncrementalOrderBookSampler
from data_manager.processing.orderbook_processor import OrderBookProcessor
from data_manager.processing.orderbook_cache_manager import OrderBookCacheManager
from data_manager.processing.orderbook_request import OrderBookSnapshotRequest
from core.orderbook import OrderBook


def assert_hftbacktest_matches_sampler(
    df_ob: pl.DataFrame,
    cache_root,
    exchange: str,
    symbol: str,
    date: date,
    levels: int,
    delta: int = 100_000_000,
    skip_hft_rows: int = 2,
    skip_sampler_rows: int = 1,
    verbose: bool = True,
):
    """
    Compare orderbook snapshots generated by hftbacktest and IncrementalOrderBookSampler.
    Raises AssertionError if they do not match within tolerance.
    """
    from polars.testing import assert_frame_equal
    from hftbacktest import BacktestAsset, HashMapMarketDepthBacktest
    from utils import get_hftbacktest_array
    from numba import njit

    @njit
    def _get_ob_sampled_njit(hbt, delta: int, levels: int):
        capacity = 100_000
        timestamps = np.empty(capacity, dtype=np.int64)
        ask_prices = np.full((capacity, levels), np.nan, dtype=np.float64)
        ask_qtys = np.full((capacity, levels), np.nan, dtype=np.float64)
        bid_prices = np.full((capacity, levels), np.nan, dtype=np.float64)
        bid_qtys = np.full((capacity, levels), np.nan, dtype=np.float64)
        row_num = 0
        while hbt.elapse(delta - hbt.current_timestamp % delta) == 0:
            if row_num >= capacity:
                new_capacity = capacity * 2
                new_timestamps = np.empty(new_capacity, dtype=np.int64)
                new_timestamps[:capacity] = timestamps
                timestamps = new_timestamps
                new_ask_prices = np.full((new_capacity, levels), np.nan, dtype=np.float64)
                new_ask_prices[:capacity] = ask_prices
                ask_prices = new_ask_prices
                new_ask_qtys = np.full((new_capacity, levels), np.nan, dtype=np.float64)
                new_ask_qtys[:capacity] = ask_qtys
                ask_qtys = new_ask_qtys
                new_bid_prices = np.full((new_capacity, levels), np.nan, dtype=np.float64)
                new_bid_prices[:capacity] = bid_prices
                bid_prices = new_bid_prices
                new_bid_qtys = np.full((new_capacity, levels), np.nan, dtype=np.float64)
                new_bid_qtys[:capacity] = bid_qtys
                bid_qtys = new_bid_qtys
                capacity = new_capacity
            depth = hbt.depth(0)
            timestamps[row_num] = hbt.current_timestamp
            _extract_orderbook_levels(
                depth, levels, ask_prices, ask_qtys, bid_prices, bid_qtys, row_num
            )
            row_num += 1
        return (
            timestamps[:row_num],
            ask_prices[:row_num],
            ask_qtys[:row_num],
            bid_prices[:row_num],
            bid_qtys[:row_num],
        )

    @njit
    def _extract_orderbook_levels(
        depth, levels, ask_prices, ask_qtys, bid_prices, bid_qtys, row_num
    ):
        tick_size = depth.tick_size
        lvl = 0
        if depth.best_ask_tick > 0:
            for tick_price in range(depth.best_ask_tick, depth.best_ask_tick + 10_000):
                qty = depth.ask_qty_at_tick(tick_price)
                if qty > 0:
                    ask_prices[row_num, lvl] = tick_price * tick_size
                    ask_qtys[row_num, lvl] = qty
                    lvl += 1
                    if lvl == levels:
                        break
        lvl = 0
        if depth.best_bid_tick > 0:
            for tick_price in range(depth.best_bid_tick, max(depth.best_bid_tick - 10_000, 0), -1):
                qty = depth.bid_qty_at_tick(tick_price)
                if qty > 0:
                    bid_prices[row_num, lvl] = tick_price * tick_size
                    bid_qtys[row_num, lvl] = qty
                    lvl += 1
                    if lvl == levels:
                        break

    def get_ob_sampled(hbt, delta: int, levels: int) -> np.ndarray:
        timestamps, ask_prices, ask_qtys, bid_prices, bid_qtys = _get_ob_sampled_njit(
            hbt, delta, levels
        )
        dtype = [("timestamp", "i8")]
        dtype.extend(
            [
                (f"{s}{i}_{t}", "f8")
                for i in range(1, levels + 1)
                for s in ["ask", "bid"]
                for t in ["price", "qty"]
            ]
        )
        num_rows = len(timestamps)
        structured_array = np.empty(num_rows, dtype=dtype)
        structured_array["timestamp"] = timestamps
        for i in range(levels):
            structured_array[f"ask{i+1}_price"] = ask_prices[:, i]
            structured_array[f"ask{i+1}_qty"] = ask_qtys[:, i]
            structured_array[f"bid{i+1}_price"] = bid_prices[:, i]
            structured_array[f"bid{i+1}_qty"] = bid_qtys[:, i]
        return structured_array

    # Generate data using hftbacktest approach
    hft_array = get_hftbacktest_array(df_ob, target_time_unit="ms")
    asset = (
        BacktestAsset()
        .data([hft_array])
        .linear_asset(1.0)
        .risk_adverse_queue_model()
        .no_partial_fill_exchange()
        .trading_value_fee_model(0.0002, 0.0007)
        .tick_size(0.1)
        .lot_size(0.001)
    )
    hbt = HashMapMarketDepthBacktest([asset])
    sampled_ob_hft = pl.DataFrame(get_ob_sampled(hbt, delta=delta, levels=levels))
    hbt.close()

    sampler = IncrementalOrderBookSampler(cache_root)
    ob_sampled = sampler.get_orderbook(
        exchange=exchange,
        symbol=symbol,
        date=date,
        levels=levels,
    ).sample_by_time(time_delta=delta, interpolate=True)
    sampled_ob_incremental = ob_sampled.df.select(sampled_ob_hft.columns)

    # Compare the two approaches (skip first few rows as hftbacktest may have different initialization)
    df1 = sampled_ob_hft[skip_hft_rows:]
    df2 = (
        sampled_ob_incremental[:-skip_sampler_rows]
        if skip_sampler_rows > 0
        else sampled_ob_incremental
    )

    assert len(df1) > 0, "hftbacktest sampled data should not be empty"
    assert len(df2) > 0, "incremental sampler data should not be empty"

    # Align lengths for fair comparison
    if len(df1) != len(df2):
        min_len = min(len(df1), len(df2))
        df1 = df1[:min_len]
        df2 = df2[:min_len]
        if verbose:
            print(f"Adjusted to common length: {min_len}")

    if verbose:
        print(f"HFT length: {len(df1)}, Incremental length: {len(df2)}")
        if len(df1) > 5:
            print("First 3 rows comparison:")
            print("HFT:", df1.head(3))
            print("Incremental:", df2.head(3))

    try:
        assert_frame_equal(df1.drop("timestamp"), df2.drop("timestamp"), abs_tol=0.0001)
    except AssertionError as e:
        print(f"Exact match failed: {e}")
        assert df1.shape == df2.shape, "DataFrames should have same shape"
        assert df1.columns == df2.columns, "DataFrames should have same columns"
        # Instead of requiring timestamps to be identical, check that they are close (within delta)
        ts1 = df1["timestamp"].to_numpy()
        ts2 = df2["timestamp"].to_numpy()
        max_diff = np.max(np.abs(ts1 - ts2))
        assert (
            max_diff <= delta
        ), f"Timestamps should be within delta ({delta}): max diff {max_diff}"
        for col in df1.columns:
            if "price" in col:
                vals1 = df1[col].drop_nulls()
                vals2 = df2[col].drop_nulls()
                if len(vals1) > 0 and len(vals2) > 0:
                    mean1 = vals1.mean()
                    mean2 = vals2.mean()
                    rel_diff = (
                        abs(mean1 - mean2) / max(mean1, mean2) if max(mean1, mean2) > 0 else 0
                    )
                    assert (
                        rel_diff < 0.01
                    ), f"Mean prices for {col} should be within 1%: {mean1} vs {mean2}"
        print("Structural similarity test passed - data patterns are consistent")


class TestDataManagerIntegrationWithRealData:
    """Integration tests using the sample real data."""

    @pytest.fixture
    def real_sample_data(self):
        """Load the real sample incremental orderbook data."""
        sample_path = ROOT_DIR / "tests" / "data_sample" / "incremental_orderbook.parquet"
        return pl.read_parquet(sample_path)

    @pytest.fixture
    def temp_data_cache(self, real_sample_data):
        """Create a temporary cache with real sample data."""
        with tempfile.TemporaryDirectory() as temp_dir:
            cache_root = Path(temp_dir)

            # Create the expected directory structure
            data_dir = cache_root / "orderbook" / "binance_futures" / "BTCUSDT"
            data_dir.mkdir(parents=True, exist_ok=True)

            # Save the sample data as if it were downloaded raw data
            # Use a date that matches the sample data timestamp range (around 2025-07-01)
            sample_date = date(2025, 7, 1)
            data_file = data_dir / f"{sample_date.strftime('%Y-%m-%d')}.parquet"

            # Prepare the data with the expected columns for processing
            processed_sample = real_sample_data.select(
                ["received_time", "event_time", "price", "quantity", "side"]
            ).with_columns(
                [
                    pl.lit("update").alias(
                        "event_type"
                    ),  # Add event_type column with "update" for all rows
                    pl.lit("BTCUSDT").alias("symbol"),  # Add symbol column
                ]
            )

            processed_sample.write_parquet(data_file)

            yield cache_root, sample_date

    def test_orderbook_processor_with_real_data(self, temp_data_cache):
        """Test OrderBookProcessor with real sample data."""
        cache_root, sample_date = temp_data_cache

        processor = OrderBookProcessor(cache_root)

        request = OrderBookSnapshotRequest(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=5,
            reference_ts="received_time",
            batch_size=10_000,  # Use smaller batch for testing
            ob_init_prev_day_rows=1000,
        )

        # Generate full event-sampled data
        result = processor.generate_full_event_sampled(request)

        # Verify the result
        assert isinstance(result, OrderBook)
        assert len(result.df) > 0

        # Check that we have the expected columns
        expected_columns = ["timestamp"]
        for i in range(1, 6):  # 5 levels
            expected_columns.extend(
                [f"ask{i}_price", f"ask{i}_qty", f"bid{i}_price", f"bid{i}_qty"]
            )

        assert all(col in result.df.columns for col in expected_columns)

        # Check that timestamps are non-decreasing
        timestamps = result.df["timestamp"].to_list()
        assert timestamps == sorted(timestamps), "Timestamps should be non-decreasing"

        # Check that we have valid price and quantity data
        # At least some ask/bid prices should be non-null
        assert result.df["ask1_price"].drop_nulls().len() > 0
        assert result.df["bid1_price"].drop_nulls().len() > 0

    def test_orderbook_cache_manager_with_real_data(self, temp_data_cache):
        """Test OrderBookCacheManager with real sample data."""
        cache_root, sample_date = temp_data_cache

        cache_manager = OrderBookCacheManager(cache_root)

        request = OrderBookSnapshotRequest(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=3,
            reference_ts="received_time",
            batch_size=5_000,
            ob_init_prev_day_rows=500,
        )

        # First call should generate new data
        result1 = cache_manager.get_cached_orderbook(request, force_regenerate=False)

        # Verify cache file was created
        cache_path = cache_root / request.get_path()
        assert cache_path.exists()

        # Second call should use cached data
        result2 = cache_manager.get_cached_orderbook(request, force_regenerate=False)

        # Results should be equivalent (same shape and columns)
        assert result1.df.shape == result2.df.shape
        assert result1.df.columns == result2.df.columns

    def test_incremental_orderbook_sampler_with_real_data(self, temp_data_cache):
        """Test IncrementalOrderBookSampler with real sample data."""
        cache_root, sample_date = temp_data_cache

        sampler = IncrementalOrderBookSampler(cache_root)

        # Test get_orderbook method
        result = sampler.get_orderbook(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=5,
            batch_size=8_000,
        )

        assert isinstance(result, OrderBook)
        assert len(result.df) > 0

        # Test that we can manipulate the result
        limited_result = result.select_levels(3)
        assert "ask4_price" not in limited_result.df.columns
        assert "ask3_price" in limited_result.df.columns

    def test_cache_hierarchy_with_real_data(self, temp_data_cache):
        """Test that cache hierarchy works correctly with different levels."""
        cache_root, sample_date = temp_data_cache

        cache_manager = OrderBookCacheManager(cache_root)

        # Generate L10 data first
        request_l10 = OrderBookSnapshotRequest(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=10,
            batch_size=5_000,
        )

        result_l10 = cache_manager.get_cached_orderbook(request_l10)
        l10_cache_path = cache_root / request_l10.get_path()
        assert l10_cache_path.exists()

        # Now request L5 data - should use L10 cache
        request_l5 = OrderBookSnapshotRequest(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=5,
            batch_size=5_000,
        )

        with patch("data_manager.processing.orderbook_cache_manager.logger") as mock_logger:
            result_l5 = cache_manager.get_cached_orderbook(request_l5)

            # Should log that it's using higher-level cache
            mock_logger.info.assert_called()
            log_calls = [call.args[0] for call in mock_logger.info.call_args_list]
            assert any("higher-level cache" in call for call in log_calls)

        # Verify L5 data is correct subset of L10
        assert len(result_l5.df) <= len(result_l10.df)
        assert "ask6_price" not in result_l5.df.columns
        assert "ask5_price" in result_l5.df.columns

    def test_data_validation_with_real_data(self, temp_data_cache):
        """Test data validation and consistency with real sample data."""
        cache_root, sample_date = temp_data_cache

        processor = OrderBookProcessor(cache_root)

        request = OrderBookSnapshotRequest(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=5,
            batch_size=10_000,
        )

        result = processor.generate_full_event_sampled(request)

        # Test data consistency
        df = result.df

        # Timestamps should be unique (no duplicates after deduplication)
        assert df["timestamp"].is_duplicated().sum() == 0

        # Ask prices should be >= bid prices at each level
        for i in range(1, 6):
            ask_col = f"ask{i}_price"
            bid_col = f"bid{i}_price"

            # Filter out null values for comparison
            valid_rows = df.filter(pl.col(ask_col).is_not_null() & pl.col(bid_col).is_not_null())

            if len(valid_rows) > 0:
                # Ask prices should generally be higher than bid prices
                spread_check = valid_rows.select(
                    (pl.col(ask_col) >= pl.col(bid_col)).alias("valid_spread")
                )
                valid_spread_ratio = spread_check["valid_spread"].mean()
                assert valid_spread_ratio > 0.8, f"Most spreads should be positive for level {i}"

        # Quantities should be positive when not null
        for i in range(1, 6):
            ask_qty_col = f"ask{i}_qty"
            bid_qty_col = f"bid{i}_qty"

            ask_qtys = df[ask_qty_col].drop_nulls()
            bid_qtys = df[bid_qty_col].drop_nulls()

            if len(ask_qtys) > 0:
                assert ask_qtys.min() > 0, f"Ask quantities should be positive for level {i}"
            if len(bid_qtys) > 0:
                assert bid_qtys.min() > 0, f"Bid quantities should be positive for level {i}"

    def test_precompute_snapshots_with_real_data(self, temp_data_cache, real_sample_data):
        """Test precompute_full_snapshots with real data for multiple dates."""
        cache_root, sample_date = temp_data_cache

        # Create data for an additional date
        data_dir = cache_root / "orderbook" / "binance_futures" / "BTCUSDT"
        next_date = sample_date + timedelta(days=1)
        next_data_file = data_dir / f"{next_date.strftime('%Y-%m-%d')}.parquet"

        # Adjust timestamps for the next day (add 24 hours in nanoseconds)
        day_in_nanos = 24 * 60 * 60 * 1_000_000_000
        next_day_data = real_sample_data.with_columns(
            [
                (pl.col("received_time") + day_in_nanos).alias("received_time"),
                (pl.col("event_time") + day_in_nanos // 1_000_000).alias(
                    "event_time"
                ),  # event_time is in milliseconds
            ]
        ).select(["received_time", "event_time", "price", "quantity", "side"])

        next_day_data.write_parquet(next_data_file)

        # Test precompute for multiple dates
        sampler = IncrementalOrderBookSampler(cache_root)

        sampler.precompute_full_snapshots(
            exchange="binance_futures",
            symbol="BTCUSDT",
            start_date=sample_date,
            end_date=next_date,
            levels=3,
            batch_size=5_000,
        )

        # Verify cache files were created for both dates
        cache_dir = cache_root / "orderbook_snapshots" / "binance_futures" / "BTCUSDT"

        cache_file_1 = cache_dir / f"{sample_date.strftime('%Y-%m-%d')}_L3.parquet"
        cache_file_2 = cache_dir / f"{next_date.strftime('%Y-%m-%d')}_L3.parquet"

        assert cache_file_1.exists()
        assert cache_file_2.exists()

        # Verify data can be loaded
        ob1 = OrderBook.from_parquet(cache_file_1)
        ob2 = OrderBook.from_parquet(cache_file_2)

        assert len(ob1.df) > 0
        assert len(ob2.df) > 0

    def test_error_handling_missing_data(self):
        """Test error handling when raw data is missing."""
        temp_dir = tempfile.mkdtemp()
        cache_root = Path(temp_dir)

        try:
            processor = OrderBookProcessor(cache_root)

            request = OrderBookSnapshotRequest(
                exchange="binance_futures",
                symbol="BTCUSDT",
                date=date(2025, 1, 1),  # Date with no data
                levels=5,
            )

            # Should raise FileNotFoundError
            with pytest.raises(FileNotFoundError):
                processor.generate_full_event_sampled(request)
        finally:
            shutil.rmtree(temp_dir)

    def test_different_reference_timestamps(self, temp_data_cache):
        """Test processing with different reference timestamp columns."""
        cache_root, sample_date = temp_data_cache

        processor = OrderBookProcessor(cache_root)

        # Test with received_time
        request_received = OrderBookSnapshotRequest(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=3,
            reference_ts="received_time",
            batch_size=5_000,
        )

        result_received = processor.generate_full_event_sampled(request_received)

        # Test with event_time
        request_event = OrderBookSnapshotRequest(
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=3,
            reference_ts="event_time",
            batch_size=5_000,
        )

        result_event = processor.generate_full_event_sampled(request_event)

        # Both should produce valid results but potentially different number of snapshots
        assert len(result_received.df) > 0
        assert len(result_event.df) > 0

        # Timestamps should be different between the two
        received_timestamps = set(result_received.df["timestamp"].to_list())
        event_timestamps = set(result_event.df["timestamp"].to_list())

        # They should have some differences (not identical)
        assert received_timestamps != event_timestamps

    @pytest.mark.slow
    def test_hftbacktest_sampled_data_matches_incremental_sampler_real_data(self, temp_data_cache):
        """Test that hftbacktest sampled data matches IncrementalOrderBookSampler with real data."""
        cache_root, sample_date = temp_data_cache
        data_file = (
            cache_root
            / "orderbook"
            / "binance_futures"
            / "BTCUSDT"
            / f"{sample_date.strftime('%Y-%m-%d')}.parquet"
        )
        df_ob = pl.read_parquet(data_file)
        df_ob = df_ob.with_columns((df_ob["event_time"] * int(1e6)).alias("event_time"))
        assert_hftbacktest_matches_sampler(
            df_ob,
            cache_root=cache_root,
            exchange="binance_futures",
            symbol="BTCUSDT",
            date=sample_date,
            levels=5,
            delta=100_000_000,
            skip_hft_rows=2,
            skip_sampler_rows=1,
            verbose=True,
        )


class TestOrderBookProcessorSyntheticData:
    """Integration tests for OrderBookProcessor with synthetic data and edge cases."""

    @pytest.fixture
    def synthetic_orderbook_data(self):
        """Create synthetic orderbook data with edge cases."""
        # Create comprehensive synthetic data with various edge cases
        data = [
            # Initial orderbook setup
            (1000, 100.0, 1.0, "bid"),
            (1000, 100.5, 2.0, "bid"),  # Multiple updates at same timestamp
            (1000, 101.0, 1.5, "ask"),
            (1000, 101.5, 2.5, "ask"),
            # Price level updates
            (1001, 99.5, 0.5, "bid"),  # New bid level
            (1001, 102.0, 1.0, "ask"),  # New ask level
            # Quantity updates
            (1002, 100.0, 1.5, "bid"),  # Update existing bid quantity
            (1002, 101.0, 2.0, "ask"),  # Update existing ask quantity
            # Price level removals
            (1003, 100.5, 0.0, "bid"),  # Remove bid level
            (1003, 101.5, 0.0, "ask"),  # Remove ask level
            # Multiple updates at same timestamp (edge case)
            (1004, 99.0, 1.0, "bid"),
            (1004, 98.5, 2.0, "bid"),
            (1004, 102.5, 1.5, "ask"),
            (1004, 103.0, 2.0, "ask"),
            # Price improvement
            (1005, 100.2, 1.2, "bid"),  # Better bid
            (1005, 100.8, 1.8, "ask"),  # Better ask
            # Large quantity update
            (1006, 99.8, 10.0, "bid"),
            (1006, 101.2, 15.0, "ask"),
            # More removals to test orderbook depth
            (1007, 99.0, 0.0, "bid"),  # Remove deeper bid
            (1007, 103.0, 0.0, "ask"),  # Remove deeper ask
            # Final updates
            (1008, 100.1, 5.0, "bid"),
            (1008, 100.9, 8.0, "ask"),
        ]

        return pl.DataFrame(
            data, schema=["received_time", "price", "quantity", "side"], orient="row"
        ).with_columns(
            [
                pl.col("received_time").alias("event_time"),  # Same timestamp for simplicity
                pl.lit("BTCUSDT").alias("symbol"),
                pl.lit("update").alias("event_type"),
            ]
        )

    @pytest.fixture
    def temp_synthetic_cache(self, synthetic_orderbook_data):
        """Create temporary cache with synthetic data."""
        with tempfile.TemporaryDirectory() as temp_dir:
            cache_root = Path(temp_dir)

            # Create directory structure
            data_dir = cache_root / "orderbook" / "test_exchange" / "BTCUSDT"
            data_dir.mkdir(parents=True, exist_ok=True)

            # Save synthetic data
            test_date = date(2025, 1, 1)
            data_file = data_dir / f"{test_date.strftime('%Y-%m-%d')}.parquet"
            synthetic_orderbook_data.write_parquet(data_file)

            yield cache_root, test_date

    def test_generate_full_event_sampled_2_levels_exact_output(self, temp_synthetic_cache):
        """Test generate_full_event_sampled with 2 levels and verify exact output."""
        cache_root, test_date = temp_synthetic_cache

        processor = OrderBookProcessor(cache_root)

        request = OrderBookSnapshotRequest(
            exchange="test_exchange",
            symbol="BTCUSDT",
            date=test_date,
            levels=2,
            reference_ts="received_time",
            batch_size=1000,
            ob_init_prev_day_rows=0,
        )

        result = processor.generate_full_event_sampled(request)

        # Verify basic structure
        assert isinstance(result, OrderBook)
        assert result.levels == 2
        assert len(result.df) > 0

        df = result.df
        # Define expected DataFrame structure
        expected_df = pl.DataFrame(
            [
                (1000, 101.0, 1.5, 100.5, 2.0, 101.5, 2.5, 100.0, 1.0),
                (1002, 101.0, 2.0, 100.5, 2.0, 101.5, 2.5, 100.0, 1.5),
                (1003, 101.0, 2.0, 100.0, 1.5, 102.0, 1.0, 99.5, 0.5),
                (1005, 100.8, 1.8, 100.2, 1.2, 101.0, 2.0, 100.0, 1.5),
                (1008, 100.8, 1.8, 100.2, 1.2, 100.9, 8.0, 100.1, 5.0),
            ],
            schema=[
                "timestamp",
                "ask1_price",
                "ask1_qty",
                "bid1_price",
                "bid1_qty",
                "ask2_price",
                "ask2_qty",
                "bid2_price",
                "bid2_qty",
            ],
            orient="row",
        )

        if not df.equals(expected_df):
            print("Actual DataFrame:")
            print(df)
            print("\nExpected DataFrame:")
            print(expected_df)
            print("\nColumn differences:")
            print(f"Actual columns: {df.columns}")
            print(f"Expected columns: {expected_df.columns}")
            print(f"Shape difference - Actual: {df.shape}, Expected: {expected_df.shape}")

            # Show row-by-row differences if same shape
            if df.shape == expected_df.shape:
                for i, (actual_row, expected_row) in enumerate(
                    zip(df.to_dicts(), expected_df.to_dicts())
                ):
                    if actual_row != expected_row:
                        print(f"\nRow {i} differs:")
                        print(f"Actual:   {actual_row}")
                        print(f"Expected: {expected_row}")

            assert False, "DataFrames are not equal - see debug output above"

    def test_generate_full_event_sampled_orderbook_depth_consistency(self, temp_synthetic_cache):
        """Test that orderbook depth is maintained consistently."""
        cache_root, test_date = temp_synthetic_cache

        processor = OrderBookProcessor(cache_root)

        request = OrderBookSnapshotRequest(
            exchange="test_exchange",
            symbol="BTCUSDT",
            date=test_date,
            levels=4,  # Request more levels than we sometimes have
            reference_ts="received_time",
            batch_size=1000,
            ob_init_prev_day_rows=0,
        )

        result = processor.generate_full_event_sampled(request)
        df = result.df

        # Check that when we don't have enough levels, the remaining are NaN
        for row_dict in df.to_dicts():
            # Count non-null bid and ask levels
            bid_levels = sum(1 for i in range(1, 5) if row_dict.get(f"bid{i}_price") is not None)
            ask_levels = sum(1 for i in range(1, 5) if row_dict.get(f"ask{i}_price") is not None)

            # Should have at least 1 level, but might not have all 4
            assert bid_levels >= 1, f"Should have at least 1 bid level, got {bid_levels}"
            assert ask_levels >= 1, f"Should have at least 1 ask level, got {ask_levels}"

            # Bid prices should be decreasing, ask prices should be increasing
            bid_prices = [row_dict.get(f"bid{i}_price") for i in range(1, bid_levels + 1)]
            ask_prices = [row_dict.get(f"ask{i}_price") for i in range(1, ask_levels + 1)]

            # Filter out None values
            valid_bid_prices = [p for p in bid_prices if p is not None]
            valid_ask_prices = [p for p in ask_prices if p is not None]

            if len(valid_bid_prices) > 1:
                assert valid_bid_prices == sorted(
                    valid_bid_prices, reverse=True
                ), "Bid prices should be decreasing"
            if len(valid_ask_prices) > 1:
                assert valid_ask_prices == sorted(
                    valid_ask_prices
                ), "Ask prices should be increasing"

    def test_generate_full_event_sampled_no_duplicate_snapshots(self, temp_synthetic_cache):
        """Test that duplicate snapshots are properly filtered out."""
        cache_root, test_date = temp_synthetic_cache

        # Create data with some identical consecutive states
        identical_state_data = [
            (1000, 100.0, 1.0, "bid"),
            (1000, 101.0, 1.0, "ask"),
            (1001, 100.0, 1.0, "bid"),  # Same as previous - should be filtered
            (1001, 101.0, 1.0, "ask"),  # Same as previous - should be filtered
            (1002, 100.0, 2.0, "bid"),  # Different quantity - should be kept
            (1002, 101.0, 1.0, "ask"),
        ]

        identical_df = pl.DataFrame(
            identical_state_data,
            schema=["received_time", "price", "quantity", "side"],
            orient="row",
        ).with_columns(
            [
                pl.col("received_time").alias("event_time"),
                pl.lit("BTCUSDT").alias("symbol"),
                pl.lit("update").alias("event_type"),
            ]
        )

        # Save this data
        data_dir = cache_root / "orderbook" / "test_exchange" / "BTCUSDT"
        identical_file = data_dir / "2025-01-02.parquet"
        identical_df.write_parquet(identical_file)

        processor = OrderBookProcessor(cache_root)

        request = OrderBookSnapshotRequest(
            exchange="test_exchange",
            symbol="BTCUSDT",
            date=date(2025, 1, 2),
            levels=2,
            reference_ts="received_time",
            batch_size=1000,
            ob_init_prev_day_rows=0,
        )

        result = processor.generate_full_event_sampled(request)
        df = result.df

        # Should only have 2 snapshots: timestamp 1000 and 1002
        # Timestamp 1001 should be filtered out as it's identical to 1000
        print(df)
        assert len(df) == 2
        timestamps = df["timestamp"].to_list()
        assert 1000 in timestamps
        assert 1002 in timestamps
        assert 1001 not in timestamps

    def test_generate_full_event_sampled_with_previous_day_initialization(self):
        """Test orderbook initialization from previous day data."""
        with tempfile.TemporaryDirectory() as temp_dir:
            cache_root = Path(temp_dir)

            # Create directory structure
            data_dir = cache_root / "orderbook" / "test_exchange" / "BTCUSDT"
            data_dir.mkdir(parents=True, exist_ok=True)

            # Create previous day data
            prev_day_data = [
                (500, 99.0, 2.0, "bid"),
                (500, 99.5, 3.0, "bid"),
                (500, 100.5, 2.5, "ask"),
                (500, 101.0, 1.5, "ask"),
            ]

            prev_df = pl.DataFrame(
                prev_day_data, schema=["received_time", "price", "quantity", "side"], orient="row"
            ).with_columns(
                [
                    pl.col("received_time").alias("event_time"),
                    pl.lit("BTCUSDT").alias("symbol"),
                    pl.lit("update").alias("event_type"),
                ]
            )

            test_date = date(2025, 1, 2)
            prev_date = test_date - timedelta(days=1)

            prev_file = data_dir / f"{prev_date.strftime('%Y-%m-%d')}.parquet"
            prev_df.write_parquet(prev_file)

            # Create current day data (fewer updates)
            current_day_data = [
                (1000, 100.0, 1.0, "bid"),  # New bid level
                (1001, 101.5, 2.0, "ask"),  # New ask level
            ]

            current_df = pl.DataFrame(
                current_day_data,
                schema=["received_time", "price", "quantity", "side"],
                orient="row",
            ).with_columns(
                [
                    pl.col("received_time").alias("event_time"),
                    pl.lit("BTCUSDT").alias("symbol"),
                    pl.lit("update").alias("event_type"),
                ]
            )

            current_file = data_dir / f"{test_date.strftime('%Y-%m-%d')}.parquet"
            current_df.write_parquet(current_file)

            processor = OrderBookProcessor(cache_root)

            request = OrderBookSnapshotRequest(
                exchange="test_exchange",
                symbol="BTCUSDT",
                date=test_date,
                levels=3,
                reference_ts="received_time",
                batch_size=1000,
                ob_init_prev_day_rows=10,
            )

            result = processor.generate_full_event_sampled(request)
            df = result.df

            # First snapshot should include previous day initialization
            first_snapshot = df.to_dicts()[0]
            assert first_snapshot["timestamp"] == 1000

            # Should have bids from previous day plus new bid
            assert first_snapshot["bid1_price"] == 100.0  # New bid (highest)
            assert first_snapshot["bid2_price"] == 99.5  # From previous day
            assert first_snapshot["bid3_price"] == 99.0  # From previous day

            # Should have asks from previous day
            assert first_snapshot["ask1_price"] == 100.5  # From previous day (lowest)
            assert first_snapshot["ask2_price"] == 101.0  # From previous day


class TestHftbacktestSampledDataSyntheticData:
    """Test hftbacktest sampled data matches IncrementalOrderBookSampler with synthetic data."""

    @pytest.fixture
    def synthetic_orderbook_data_for_hft(self):
        """Create synthetic orderbook data suitable for hftbacktest comparison."""
        # Create more comprehensive synthetic data
        data = [
            # Initial state
            (1000_000_000, 100.0, 1.0, "bid"),
            (1000_000_000, 100.5, 2.0, "bid"),
            (1000_000_000, 101.0, 1.5, "ask"),
            (1000_000_000, 101.5, 2.5, "ask"),
            # Update at 100ms later
            (1100_000_000, 99.5, 0.5, "bid"),
            (1100_000_000, 102.0, 1.0, "ask"),
            # Update at 200ms later
            (1200_000_000, 100.0, 1.5, "bid"),
            (1200_000_000, 101.0, 2.0, "ask"),
            # Update at 300ms later (remove some levels)
            (1300_000_000, 100.5, 0.0, "bid"),  # Remove level
            (1300_000_000, 101.5, 0.0, "ask"),  # Remove level
            # Update at 400ms later
            (1400_000_000, 99.0, 1.0, "bid"),
            (1400_000_000, 98.5, 2.0, "bid"),
            (1400_000_000, 102.5, 1.5, "ask"),
            (1400_000_000, 103.0, 2.0, "ask"),
            # More updates
            (1500_000_000, 100.2, 1.2, "bid"),
            (1500_000_000, 100.8, 1.8, "ask"),
            # Final updates
            (1600_000_000, 99.8, 10.0, "bid"),
            (1600_000_000, 101.2, 15.0, "ask"),
        ]

        return pl.DataFrame(
            data, schema=["received_time", "price", "quantity", "side"], orient="row"
        ).with_columns(
            [
                pl.col("received_time").alias("event_time"),
                pl.lit("BTCUSDT").alias("symbol"),
                pl.lit("update").alias("event_type"),
            ]
        )

    @pytest.fixture
    def temp_synthetic_cache_for_hft(self, synthetic_orderbook_data_for_hft):
        """Create temporary cache with synthetic data for hftbacktest comparison."""
        with tempfile.TemporaryDirectory() as temp_dir:
            cache_root = Path(temp_dir)

            # Create directory structure
            data_dir = cache_root / "orderbook" / "test_exchange" / "BTCUSDT"
            data_dir.mkdir(parents=True, exist_ok=True)

            test_date = date(2025, 1, 1)
            data_file = data_dir / f"{test_date.strftime('%Y-%m-%d')}.parquet"
            synthetic_orderbook_data_for_hft.write_parquet(data_file)

            yield cache_root, test_date

    @pytest.mark.slow
    def test_hftbacktest_sampled_data_matches_incremental_sampler_synthetic_data(
        self, temp_synthetic_cache_for_hft
    ):
        """Test that hftbacktest sampled data matches IncrementalOrderBookSampler with synthetic data."""

        cache_root, test_date = temp_synthetic_cache_for_hft
        data_file = (
            cache_root
            / "orderbook"
            / "test_exchange"
            / "BTCUSDT"
            / f"{test_date.strftime('%Y-%m-%d')}.parquet"
        )
        df_ob = pl.read_parquet(data_file)
        assert_hftbacktest_matches_sampler(
            df_ob,
            cache_root=cache_root,
            exchange="test_exchange",
            symbol="BTCUSDT",
            date=test_date,
            levels=3,
            delta=100_000_000,
            skip_hft_rows=0,
            skip_sampler_rows=0,
            verbose=True,
        )
