data:
  device: "cuda"
  source: "embeddings"
  embedding_code: "chronos2-base_ctx512_seqlast_s5"
  pca_components: 512
  stride: 1

model:
  type: "transformer"
  sequence_length: 100
  d_model: 32
  nhead: 4
  num_layers: 2
  dropout: 0.2
  dim_feedforward: 128
  activation: "relu"
  learned_positional_encoding: true

training:
  mixed_precision: true

logging:
  project_name: "final_experiments"
  experiment_name_prefix: "small_transformer_PCA"
