data_type:
  - orderbook
  - trades
symbol: BTCUSDT
exchange:
  - binance_futures
  - binance_spot
relevant_features_path: "config/data_manager/relevant_features.yaml"
reference_ts: "received_time"
dates:
  start_date: "2025-07-01"
  end_date: "2025-07-31" # If null, use today's date
